// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: pb/school.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Grade int32

const (
	Grade_FirstGrade  Grade = 0
	Grade_SecondGrade Grade = 1
	Grade_ThirdGrade  Grade = 2
	Grade_FourthGrade Grade = 3
	Grade_FifthGrade  Grade = 4
	Grade_SixthGrade  Grade = 5
)

// Enum value maps for Grade.
var (
	Grade_name = map[int32]string{
		0: "FirstGrade",
		1: "SecondGrade",
		2: "ThirdGrade",
		3: "FourthGrade",
		4: "FifthGrade",
		5: "SixthGrade",
	}
	Grade_value = map[string]int32{
		"FirstGrade":  0,
		"SecondGrade": 1,
		"ThirdGrade":  2,
		"FourthGrade": 3,
		"FifthGrade":  4,
		"SixthGrade":  5,
	}
)

func (x Grade) Enum() *Grade {
	p := new(Grade)
	*p = x
	return p
}

func (x Grade) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grade) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_school_proto_enumTypes[0].Descriptor()
}

func (Grade) Type() protoreflect.EnumType {
	return &file_pb_school_proto_enumTypes[0]
}

func (x Grade) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grade.Descriptor instead.
func (Grade) EnumDescriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{0}
}

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Male   bool    `protobuf:"varint,2,opt,name=male,proto3" json:"male,omitempty"`
	Scores []int32 `protobuf:"varint,3,rep,packed,name=scores,proto3" json:"scores,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_school_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_pb_school_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetMale() bool {
	if x != nil {
		return x.Male
	}
	return false
}

func (x *Student) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type Class struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Students []*Student `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	Grade    Grade      `protobuf:"varint,2,opt,name=grade,proto3,enum=pb.Grade" json:"grade,omitempty"`
	Class    int32      `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"`
}

func (x *Class) Reset() {
	*x = Class{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_school_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_pb_school_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{1}
}

func (x *Class) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *Class) GetGrade() Grade {
	if x != nil {
		return x.Grade
	}
	return Grade_FirstGrade
}

func (x *Class) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

type School struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classes []*Class `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *School) Reset() {
	*x = School{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_school_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *School) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*School) ProtoMessage() {}

func (x *School) ProtoReflect() protoreflect.Message {
	mi := &file_pb_school_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use School.ProtoReflect.Descriptor instead.
func (*School) Descriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{2}
}

func (x *School) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *School) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSchoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetSchoolRequest) Reset() {
	*x = GetSchoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_school_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSchoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolRequest) ProtoMessage() {}

func (x *GetSchoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_school_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolRequest.ProtoReflect.Descriptor instead.
func (*GetSchoolRequest) Descriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchoolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSchoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *School `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetSchoolResponse) Reset() {
	*x = GetSchoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_school_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSchoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolResponse) ProtoMessage() {}

func (x *GetSchoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_school_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolResponse.ProtoReflect.Descriptor instead.
func (*GetSchoolResponse) Descriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchoolResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSchoolResponse) GetData() *School {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSchoolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WebResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WebResponse) Reset() {
	*x = WebResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_school_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebResponse) ProtoMessage() {}

func (x *WebResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_school_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebResponse.ProtoReflect.Descriptor instead.
func (*WebResponse) Descriptor() ([]byte, []int) {
	return file_pb_school_proto_rawDescGZIP(), []int{5}
}

func (x *WebResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WebResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_school_proto protoreflect.FileDescriptor

var file_pb_school_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x49, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x67, 0x0a,
	0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x1f, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x12, 0x23, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x07, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x61, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x57, 0x65, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2a, 0x69, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x47, 0x72, 0x61, 0x64, 0x65, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54,
	0x68, 0x69, 0x72, 0x64, 0x47, 0x72, 0x61, 0x64, 0x65, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x46,
	0x6f, 0x75, 0x72, 0x74, 0x68, 0x47, 0x72, 0x61, 0x64, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a,
	0x46, 0x69, 0x66, 0x74, 0x68, 0x47, 0x72, 0x61, 0x64, 0x65, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x69, 0x78, 0x74, 0x68, 0x47, 0x72, 0x61, 0x64, 0x65, 0x10, 0x05, 0x32, 0xab, 0x01, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x2e, 0x0a, 0x0c, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x65, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_school_proto_rawDescOnce sync.Once
	file_pb_school_proto_rawDescData = file_pb_school_proto_rawDesc
)

func file_pb_school_proto_rawDescGZIP() []byte {
	file_pb_school_proto_rawDescOnce.Do(func() {
		file_pb_school_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_school_proto_rawDescData)
	})
	return file_pb_school_proto_rawDescData
}

var file_pb_school_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_school_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_school_proto_goTypes = []interface{}{
	(Grade)(0),                // 0: pb.Grade
	(*Student)(nil),           // 1: pb.Student
	(*Class)(nil),             // 2: pb.Class
	(*School)(nil),            // 3: pb.School
	(*GetSchoolRequest)(nil),  // 4: pb.GetSchoolRequest
	(*GetSchoolResponse)(nil), // 5: pb.GetSchoolResponse
	(*WebResponse)(nil),       // 6: pb.WebResponse
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_pb_school_proto_depIdxs = []int32{
	1, // 0: pb.Class.students:type_name -> pb.Student
	0, // 1: pb.Class.grade:type_name -> pb.Grade
	2, // 2: pb.School.classes:type_name -> pb.Class
	3, // 3: pb.GetSchoolResponse.data:type_name -> pb.School
	4, // 4: pb.GetSchool.GetSchool:input_type -> pb.GetSchoolRequest
	7, // 5: pb.GetSchool.GetStudents:input_type -> google.protobuf.Empty
	1, // 6: pb.GetSchool.SendStudents:input_type -> pb.Student
	5, // 7: pb.GetSchool.GetSchool:output_type -> pb.GetSchoolResponse
	1, // 8: pb.GetSchool.GetStudents:output_type -> pb.Student
	6, // 9: pb.GetSchool.SendStudents:output_type -> pb.WebResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_school_proto_init() }
func file_pb_school_proto_init() {
	if File_pb_school_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_school_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_school_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_school_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*School); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_school_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSchoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_school_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSchoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_school_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_school_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_school_proto_goTypes,
		DependencyIndexes: file_pb_school_proto_depIdxs,
		EnumInfos:         file_pb_school_proto_enumTypes,
		MessageInfos:      file_pb_school_proto_msgTypes,
	}.Build()
	File_pb_school_proto = out.File
	file_pb_school_proto_rawDesc = nil
	file_pb_school_proto_goTypes = nil
	file_pb_school_proto_depIdxs = nil
}
